<link rel="stylesheet" href="{{ asset('user/css/linearicons.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/bootstrap.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/owl.carousel.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/nouislider.min.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/ion.rangeSlider.css') }}"/>
<link rel="stylesheet" href="{{ asset('user/css/ion.rangeSlider.skinFlat.css') }}"/>
<link rel="stylesheet" href="{{ asset('user/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('user/css/main.css') }}">
